/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import entidad.Administrador;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.AdministradorData;

/**
 *
 * @author Usuario
 */
public class AgregarAdminRegistro extends javax.swing.JInternalFrame {

    DefaultTableModel model = null;
    AdministradorData ad = null;
    
    
    public AgregarAdminRegistro() {
        initComponents();
        PanelAgregar.setVisible(false);
        BotonEliminar.setEnabled(false);
        
        model = new DefaultTableModel();
        ad = new AdministradorData();
        
        cargarModelo();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelRegistro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UsuarioAd = new javax.swing.JTextField();
        ContraseñaAd = new javax.swing.JPasswordField();
        IngresarBT = new javax.swing.JButton();
        PanelAgregar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAdmins = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UsuarioText = new javax.swing.JTextField();
        ContraseñaText = new javax.swing.JPasswordField();
        BotonGuardar = new javax.swing.JButton();
        BotonEliminar = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Administracion");

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SECCION HABILITADA SOLO PARA EL CEO DE LA EMPRESA, REGISTRESE: ");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Usuario: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Contraseña:");

        IngresarBT.setBackground(new java.awt.Color(153, 255, 153));
        IngresarBT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IngresarBT.setText("Ingresar");
        IngresarBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarBTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelRegistroLayout = new javax.swing.GroupLayout(PanelRegistro);
        PanelRegistro.setLayout(PanelRegistroLayout);
        PanelRegistroLayout.setHorizontalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(61, 61, 61)
                        .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContraseñaAd, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UsuarioAd, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelRegistroLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(IngresarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelRegistroLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );
        PanelRegistroLayout.setVerticalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelRegistroLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(UsuarioAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ContraseñaAd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(IngresarBT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jPanel1.add(PanelRegistro, "card2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADMINISTRADORES");

        TablaAdmins.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaAdmins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAdminsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaAdmins);

        jLabel5.setText("Usuario:");

        jLabel6.setText("Contraseña:");

        ContraseñaText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ContraseñaTextKeyTyped(evt);
            }
        });

        BotonGuardar.setBackground(new java.awt.Color(153, 255, 102));
        BotonGuardar.setText("Guardar");
        BotonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarActionPerformed(evt);
            }
        });

        BotonEliminar.setBackground(new java.awt.Color(255, 51, 51));
        BotonEliminar.setText("Eliminar");
        BotonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarActionPerformed(evt);
            }
        });

        BotonActualizar.setBackground(new java.awt.Color(102, 153, 255));
        BotonActualizar.setText("Actualizar");
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAgregarLayout = new javax.swing.GroupLayout(PanelAgregar);
        PanelAgregar.setLayout(PanelAgregarLayout);
        PanelAgregarLayout.setHorizontalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarLayout.createSequentialGroup()
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(29, 29, 29)
                                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ContraseñaText, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                    .addComponent(UsuarioText))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BotonGuardar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BotonActualizar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BotonEliminar, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        PanelAgregarLayout.setVerticalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(UsuarioText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonGuardar))
                .addGap(18, 18, 18)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ContraseñaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonActualizar))
                .addGap(18, 18, 18)
                .addComponent(BotonEliminar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel1.add(PanelAgregar, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngresarBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarBTActionPerformed
        // TODO add your handling code here:

        String usuario = UsuarioAd.getText();
        String contraseña = ContraseñaAd.getText();

        if (usuario.equals("CEO123") && contraseña.equals("adminceo")) {
            JOptionPane.showMessageDialog(this, "Ingreso Correcto! Bienvenido", "ÉXITO!", JOptionPane.INFORMATION_MESSAGE);
            PanelRegistro.setVisible(false);
            PanelAgregar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Ingreso Incorrecto! Verifique sus Credenciales", "ERROR!", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_IngresarBTActionPerformed

    private void BotonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarActionPerformed
        // TODO add your handling code here:
        
        try{
            if (!"".equals(UsuarioText.getText()) || !"".equals(ContraseñaText.getText())) {
            String usuario = UsuarioText.getText();
            int contraseña = Integer.parseInt(ContraseñaText.getText());
            
            Administrador admin = new Administrador(usuario, contraseña);
            ad.guardarAdministrador(admin);
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Administrador Agregado", "Exito", JOptionPane.INFORMATION_MESSAGE);
            
        } else {
            JOptionPane.showMessageDialog(this, "Complete Todos los Campos", "Campos Vacios", JOptionPane.ERROR_MESSAGE);
        }
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this,  "Complete Todos los Campos", "Campos Vacios", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BotonGuardarActionPerformed

    private void ContraseñaTextKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContraseñaTextKeyTyped
        
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            evt.consume(); 
        }
        
    }//GEN-LAST:event_ContraseñaTextKeyTyped

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        // TODO add your handling code here:
        model.setRowCount(0);
        cargarDatos();
        BotonEliminar.setEnabled(false);
        ContraseñaText.setVisible(true);
        ContraseñaText.setEnabled(true);
        UsuarioText.setEnabled(true);
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void BotonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarActionPerformed
        
        if (!"".equals(UsuarioText.getText())) {
            
            ad.borrarAdmin(UsuarioText.getText());
            
            limpiarCampos();
            BotonEliminar.setEnabled(false);
            ContraseñaText.setVisible(true);
            ContraseñaText.setEnabled(true);
            UsuarioText.setEnabled(true);
            
        } else {
            JOptionPane.showMessageDialog(this, "Complete Todos los Campos", "Campos Vacios", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_BotonEliminarActionPerformed

    private void TablaAdminsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAdminsMouseClicked
        
        int select = TablaAdmins.getSelectedRow();
        BotonEliminar.setEnabled(true);
        UsuarioText.setEnabled(false);
        ContraseñaText.setEnabled(false);
        
        UsuarioText.setText((String)TablaAdmins.getValueAt(select, 0));
        ContraseñaText.setVisible(false);
        
    }//GEN-LAST:event_TablaAdminsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonEliminar;
    private javax.swing.JButton BotonGuardar;
    private javax.swing.JPasswordField ContraseñaAd;
    private javax.swing.JPasswordField ContraseñaText;
    private javax.swing.JButton IngresarBT;
    private javax.swing.JPanel PanelAgregar;
    private javax.swing.JPanel PanelRegistro;
    private javax.swing.JTable TablaAdmins;
    private javax.swing.JTextField UsuarioAd;
    private javax.swing.JTextField UsuarioText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void cargarModelo(){
        
        ArrayList<Object> columnas = new ArrayList();
        
        columnas.add("Usuario");
        columnas.add("Contraseña");
        
        for (Object aux : columnas) {
            model.addColumn(aux);
        }
        
        TablaAdmins.setModel(model);
    }
    
    private void cargarDatos(){
        List <Administrador> admins = ad.listarAdmins();
        
        for (Administrador aux : admins) {
            model.addRow(new Object[]{
                aux.getUsuario(),
                aux.getContraseña()
            });
        }
    }
    
    private void limpiarCampos(){
        UsuarioText.setText("");
        ContraseñaText.setText("");
    }
    
}
