/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.io.InputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

/**
 *
 * @author Celi Leandro
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        setTitle("Travel Together");
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        activeLogin();
        desactivarOpcionesAdmin();

    }

    public void activarOpcionesAdmin() {
        jMenuGestionDatos.setVisible(true);
        jMenuConfiguracion.setVisible(true);
        jMenuEstadisticas.setVisible(true);
    }

    public void desactivarOpcionesAdmin() {
        jMenuGestionDatos.setVisible(false);
        jMenuConfiguracion.setVisible(false);
        jMenuEstadisticas.setVisible(false);
    }

    public void disambleLogin() {
        jMenuInicio.setVisible(false);
        jMenuCerrarSesion.setVisible(true);
    }

    public void activeLogin() {
        jMenuInicio.setVisible(true);
        jMenuCerrarSesion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        ImageIcon imagen = new ImageIcon(getClass().getResource("/imagenes/imagen.jpg"));
        Image miImagen = imagen.getImage();
        jDesktopPanePrincipal = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen, 0, 0, getWidth(), getHeight(), this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuCerrarSesion = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuCrearPaquete = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuGestionDatos = new javax.swing.JMenu();
        MenuCiudad = new javax.swing.JMenuItem();
        MenuAlojamiento = new javax.swing.JMenuItem();
        jMenuEstadisticas = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuConfiguracion = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem10.setText("jMenuItem10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        jMenuInicio.setText("Inicio");

        jMenuItem9.setText("Iniciar sesión");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenuInicio.add(jMenuItem9);

        jMenuBar1.add(jMenuInicio);

        jMenuCerrarSesion.setText("Inicio");
        jMenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCerrarSesionActionPerformed(evt);
            }
        });

        jMenuItem12.setText("Cerrar Sesion");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenuCerrarSesion.add(jMenuItem12);

        jMenuBar1.add(jMenuCerrarSesion);

        jMenu3.setText("Paquetes");

        jMenuItem5.setText("Buscar Paquete");
        jMenu3.add(jMenuItem5);

        MenuCrearPaquete.setText("Crear Paquete");
        MenuCrearPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCrearPaqueteActionPerformed(evt);
            }
        });
        jMenu3.add(MenuCrearPaquete);

        jMenuItem13.setText("Comprar Pasaje");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        jMenuGestionDatos.setText("Gestion de Datos");
        jMenuGestionDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGestionDatosActionPerformed(evt);
            }
        });

        MenuCiudad.setText("Ciudad");
        MenuCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCiudadActionPerformed(evt);
            }
        });
        jMenuGestionDatos.add(MenuCiudad);

        MenuAlojamiento.setText("Alojamiento");
        MenuAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAlojamientoActionPerformed(evt);
            }
        });
        jMenuGestionDatos.add(MenuAlojamiento);

        jMenuBar1.add(jMenuGestionDatos);

        jMenuEstadisticas.setText("Estadisticas");

        jMenuItem7.setText("Estadisticas");
        jMenuEstadisticas.add(jMenuItem7);

        jMenuItem8.setText("Generar Reportes");
        jMenuEstadisticas.add(jMenuItem8);

        jMenuBar1.add(jMenuEstadisticas);

        jMenuConfiguracion.setText("Configuracion");
        jMenuBar1.add(jMenuConfiguracion);

        jMenu7.setText("Ayuda");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCiudadActionPerformed
        repintarEscritorio();
        VistaGCiudad gestionCiudad = new VistaGCiudad();
        jDesktopPanePrincipal.add(gestionCiudad);
        centrarVista(gestionCiudad);   
        gestionCiudad.setVisible(true);     
    }//GEN-LAST:event_MenuCiudadActionPerformed

    private void jMenuGestionDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGestionDatosActionPerformed

    }//GEN-LAST:event_jMenuGestionDatosActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        repintarEscritorio();
        VistaInicioSesion inicioSesion = new VistaInicioSesion(this);
        jDesktopPanePrincipal.add(inicioSesion);
        centrarVista(inicioSesion);
        inicioSesion.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCerrarSesionActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuCerrarSesionActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        desactivarOpcionesAdmin();
        activeLogin();// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void MenuAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAlojamientoActionPerformed
        repintarEscritorio();
        VistaAlojamiento vistaAlo = new VistaAlojamiento();
        jDesktopPanePrincipal.add(vistaAlo);
        centrarVista(vistaAlo);
        vistaAlo.setVisible(true);
    }//GEN-LAST:event_MenuAlojamientoActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        repintarEscritorio();
        VistaPasaje vistaPas = new VistaPasaje();
        jDesktopPanePrincipal.add(vistaPas);
        centrarVista(vistaPas);
        vistaPas.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void MenuCrearPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCrearPaqueteActionPerformed
        repintarEscritorio();
        VistaCrearPaquete vistaCP = new VistaCrearPaquete();
        jDesktopPanePrincipal.add(vistaCP);
        centrarVista(vistaCP);
        vistaCP.setVisible(true);
    }//GEN-LAST:event_MenuCrearPaqueteActionPerformed
    
    public void centrarVista(JInternalFrame vista){
        int x = (jDesktopPanePrincipal.getWidth() - vista.getWidth()) / 2;
        int y = (jDesktopPanePrincipal.getHeight() - vista.getHeight()) / 2;
        vista.setLocation(x, y);
    }

    public void repintarEscritorio(){
        jDesktopPanePrincipal.removeAll();
        jDesktopPanePrincipal.revalidate();
        jDesktopPanePrincipal.repaint(); 
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAlojamiento;
    private javax.swing.JMenuItem MenuCiudad;
    private javax.swing.JMenuItem MenuCrearPaquete;
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCerrarSesion;
    private javax.swing.JMenu jMenuConfiguracion;
    private javax.swing.JMenu jMenuEstadisticas;
    private javax.swing.JMenu jMenuGestionDatos;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
