/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import entidad.Ciudad;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import persistencia.ComprasData;

/**
 *
 * @author Usuario
 */
public class VistaMasConcurridas extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    Ciudad ciudad = null;
    ComprasData cd = null;
    
    public VistaMasConcurridas() {
        initComponents();
        
        GrupoBoton.add(RadioMes);
        GrupoBoton.add(RadioTemporada);
        
        ComboMes.setEnabled(false);
        ComboTemporada.setEnabled(false);
        
        model = new DefaultTableModel();
        cd = new ComprasData();
        
        CargarModelo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBoton = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ComboMes = new javax.swing.JComboBox<>();
        ComboTemporada = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPaquetes = new javax.swing.JTable();
        RadioMes = new javax.swing.JRadioButton();
        RadioTemporada = new javax.swing.JRadioButton();
        TextCiudad = new javax.swing.JTextField();

        ComboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiempre", "Ocutubre", "Noviembre", "Diciembre" }));

        ComboTemporada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Alta", "Baja", "Media" }));

        TablaPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaPaquetes);

        RadioMes.setText("MES");
        RadioMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioMesActionPerformed(evt);
            }
        });

        RadioTemporada.setText("TEMPORADA");
        RadioTemporada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioTemporadaActionPerformed(evt);
            }
        });

        TextCiudad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TextCiudad.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RadioTemporada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboTemporada, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(RadioMes)
                                .addGap(51, 51, 51)
                                .addComponent(ComboMes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)))
                        .addComponent(TextCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioMes))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboTemporada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioTemporada)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(TextCiudad)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioMesActionPerformed
        // TODO add your handling code here:
        ComboTemporada.setEnabled(false);
        ComboMes.setEnabled(true);
    }//GEN-LAST:event_RadioMesActionPerformed

    private void RadioTemporadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioTemporadaActionPerformed
        // TODO add your handling code here:
        ComboMes.setEnabled(false);
        ComboTemporada.setEnabled(true);
    }//GEN-LAST:event_RadioTemporadaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboMes;
    private javax.swing.JComboBox<String> ComboTemporada;
    private javax.swing.ButtonGroup GrupoBoton;
    private javax.swing.JRadioButton RadioMes;
    private javax.swing.JRadioButton RadioTemporada;
    private javax.swing.JTable TablaPaquetes;
    private javax.swing.JTextField TextCiudad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void CargarModelo(){
        ArrayList<Object> columnas = new ArrayList();
        
        columnas.add("idCompra");
        columnas.add("codPaquete");
        columnas.add("ciudad");
        columnas.add("temporada");
        
        for (Object aux : columnas) {
            model.addColumn(aux);
        }
        
        TablaPaquetes.setModel(model);
    }

    
}
